from __future__ import annotations

MODEL_DIMS: dict[str, dict[str, list[str]]] = {
    "macbookpro": {
        "dimensionScreensize": ["14inch", "16inch"],
        "tsMemorySize": ["16gb", "18gb", "24gb", "32gb", "36gb", "48gb", "64gb", "96gb", "128gb", "192gb"],
        "dimensionCapacity": ["256gb", "512gb", "1tb", "2tb", "4tb", "8tb"],
        "dimensionColor": ["silver", "spaceblack", "space_gray"],
        "dimensionRelYear": ["2022", "2023", "2024", "2025", "2026"],
        "chip": ["m3_pro", "m3_max", "m4", "m4_pro", "m4_max", "m5", "m5_pro", "m5_max"],
    },
    "macbookair": {
        "dimensionScreensize": ["13inch", "15inch"],
        "tsMemorySize": ["16gb", "24gb", "32gb"],
        "dimensionCapacity": ["256gb", "512gb", "1tb", "2tb"],
        "dimensionColor": ["silver", "starlight", "midnight", "skyblue", "space_gray"],
        "dimensionRelYear": ["2024", "2025", "2026"],
        "chip": ["m2", "m3", "m4", "m5"],
    },
    "macbookneo": {
        "dimensionScreensize": ["13inch"],
        "tsMemorySize": ["16gb", "24gb"],
        "dimensionCapacity": ["256gb", "512gb", "1tb"],
        "dimensionColor": ["silver", "blush", "citrus", "indigo"],
        "dimensionRelYear": ["2026"],
        "chip": ["a18_pro"],
    },
    "imac": {
        "dimensionScreensize": ["24inch"],
        "tsMemorySize": ["8gb", "16gb", "24gb", "32gb"],
        "dimensionCapacity": ["256gb", "512gb", "1tb", "2tb"],
        "dimensionColor": ["silver", "blue", "green", "pink", "yellow", "orange", "purple"],
        "dimensionRelYear": ["2023", "2024", "2025"],
        "chip": ["m3", "m4"],
    },
    "macmini": {
        "tsMemorySize": ["8gb", "16gb", "24gb", "32gb"],
        "dimensionCapacity": ["256gb", "512gb", "1tb", "2tb", "4tb"],
        "dimensionColor": ["silver"],
        "dimensionRelYear": ["2023", "2024", "2025", "2026"],
        "chip": ["m2", "m2_pro", "m4", "m4_pro"],
    },
    "macstudio": {
        "tsMemorySize": ["32gb", "36gb", "48gb", "64gb", "96gb", "128gb", "192gb"],
        "dimensionCapacity": ["512gb", "1tb", "2tb", "4tb", "8tb"],
        "dimensionRelYear": ["2023", "2025"],
        "chip": ["m2_max", "m2_ultra", "m4_max"],
    },
    "macpro": {
        "tsMemorySize": ["96gb", "192gb", "768gb", "1_5tb"],
        "dimensionCapacity": ["1tb", "2tb", "4tb", "8tb"],
        "dimensionColor": ["silver"],
        "dimensionRelYear": ["2019", "2023"],
        "chip": ["m2_ultra"],
    },
    "display": {
        "dimensionScreensize": ["27inch"],
        "dimensionRelYear": ["2022", "2024", "2026"],
    },
    "ipad2017": {
        "dimensionScreensize": ["10_9inch"],
        "dimensionCapacity": ["64gb", "128gb", "256gb", "512gb"],
        "dimensionColor": ["blue", "pink", "silver", "yellow"],
        "dimensionconnectivity": ["wifi", "wificell"],
        "dimensionRelYear": ["2022", "2025"],
        "chip": ["a16"],
    },
    "ipadair_10_9": {
        "dimensionScreensize": ["10_9inch"],
        "dimensionCapacity": ["64gb", "128gb", "256gb"],
        "dimensionconnectivity": ["wifi", "wificell"],
        "chip": ["m1", "m2"],
    },
    "ipadair_11": {
        "dimensionScreensize": ["11inch"],
        "dimensionCapacity": ["128gb", "256gb", "512gb", "1tb"],
        "dimensionColor": ["blue", "purple", "space_gray", "starlight"],
        "dimensionconnectivity": ["wifi", "wificell"],
        "dimensionRelYear": ["2025"],
        "chip": ["m2", "m3"],
    },
    "ipadair_13": {
        "dimensionScreensize": ["13inch"],
        "dimensionCapacity": ["128gb", "256gb", "512gb", "1tb"],
        "dimensionColor": ["blue", "purple", "space_gray", "starlight"],
        "dimensionconnectivity": ["wifi", "wificell"],
        "dimensionRelYear": ["2024", "2025"],
        "chip": ["m2", "m3"],
    },
    "ipadpro_11": {
        "dimensionScreensize": ["11inch"],
        "dimensionCapacity": ["128gb", "256gb", "512gb", "1tb", "2tb"],
        "dimensionColor": ["silver", "space_gray"],
        "dimensionconnectivity": ["wifi", "wificell"],
        "dimensionRelYear": ["2022", "2024"],
        "chip": ["m2", "m4"],
    },
    "ipadpro_12_9": {
        "dimensionScreensize": ["12_9inch"],
        "dimensionCapacity": ["128gb", "256gb", "512gb", "1tb", "2tb"],
        "dimensionColor": ["silver", "space_gray"],
        "dimensionconnectivity": ["wifi", "wificell"],
        "dimensionRelYear": ["2022"],
        "chip": ["m2"],
    },
    "ipadpro_13": {
        "dimensionScreensize": ["13inch"],
        "dimensionCapacity": ["256gb", "512gb", "1tb", "2tb"],
        "dimensionColor": ["silver", "space_gray"],
        "dimensionconnectivity": ["wifi", "wificell"],
        "dimensionRelYear": ["2024"],
        "chip": ["m4"],
    },
    "ipadmini6": {
        "dimensionScreensize": ["8_3inch"],
        "dimensionCapacity": ["64gb", "256gb"],
        "dimensionColor": ["purple", "space_gray", "starlight", "pink"],
        "dimensionconnectivity": ["wifi", "wificell"],
        "dimensionRelYear": ["2021"],
        "chip": ["a15"],
    },
    "watchseries9": {
        "dimensionCaseSize": ["41mm", "45mm"],
        "dimensionCaseMaterial": ["aluminum", "stainless"],
        "dimensionConnection": ["gps", "gpscell"],
    },
    "watchseries10": {
        "dimensionCaseSize": ["42mm", "46mm"],
        "dimensionCaseMaterial": ["aluminum", "titanium"],
        "dimensionConnection": ["gps", "gpscell"],
    },
    "watchseries11": {
        "dimensionCaseSize": ["42mm", "46mm"],
        "dimensionCaseMaterial": ["aluminum", "titanium"],
        "dimensionConnection": ["gps", "gpscell"],
    },
    "watchse2": {
        "dimensionCaseSize": ["40mm", "44mm"],
        "dimensionCaseMaterial": ["aluminum"],
        "dimensionConnection": ["gps", "gpscell"],
    },
    "watchse3": {
        "dimensionCaseSize": ["40mm", "44mm"],
        "dimensionCaseMaterial": ["aluminum"],
        "dimensionConnection": ["gps", "gpscell"],
    },
    "watchultra2": {
        "dimensionCaseSize": ["49mm"],
        "dimensionCaseMaterial": ["titanium"],
        "dimensionConnection": ["gpscell"],
    },
    "watchultra3": {
        "dimensionCaseSize": ["49mm"],
        "dimensionCaseMaterial": ["titanium"],
        "dimensionConnection": ["gpscell"],
    },
}
